Fix CAS1 test instability
This test could previously fail with errors like the following:

```
  java.time.format.DateTimeParseException: Text '2025-05-22T05:22Z' could not be parsed at index 16
      at uk.gov.justice.digital.hmpps.approvedpremisesapi.integration.cas1.Cas1ApplicationTest$GetApplicationsMe.Get_applications_me_returns_twelve_items_sorted_by_created_at_asc$lambda$3$lambda$2(Cas1ApplicationTest.kt:852)
```

I think this happens when the time is on 0 seconds. This commit should fix that issue by no longer converting dates to a string.

This commit also adds some generated components missed by prioir commits