Remove static mocks from PreemptiveCacheTest
Static mocks are tricky because you need to re-member to unset them once done. We’ve also found that mocking a commonly used function (`Instant.now()`) lead to errors when some other code used the the function before we’d had a chance to set a response e.g.

```
2025-06-03 14:26:34.375 ERROR 452 --- [Container#0-0-1] c.s.l.a.BatchingAcknowledgementProcessor : Error executing scheduled acknowledgement in io.awspring.cloud.sqs.sqsListenerEndpointContainer#0-0. Resuming. |

io.mockk.MockKException: no answer provided for class java.time.Instant.now())
```

This commit removes use of static mocks in PreemptiveCacheTest and replaces it with the pre-existing mutable clock