Change from = null to is null.
"= null" criteria was causing the SQL to return 0 records for this test:
'it should migrate notice types of applications()'

with the following error:
org.opentest4j.AssertionFailedError: expected: shortNotice but was: null at java.base@21.0.2/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) at java.base@21.0.2/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) at